### ISSUE TITLE
Users do not get a response and stay on the same page after clicking Register Now 

### ISSUE THREAD

**Issue by Jingwnpn** [info-461-TBD/ShelterConnect#44]
<img width="298" alt="screen shot 2018-06-03 at 7 59 54 pm" src="https://user-images.githubusercontent.com/22405025/40896239-b6957e58-6768-11e8-9cad-411a2cbd22af.png">

**Comment by rykerls** [comment]
Hi @Jingwnpn,

Thanks for pointing this out. It looks like we forgot to actually include a link there. I have since added a link and merged it into our master branch. We will release a patched version of our app later today.

Cheers,
Ryker
