### ISSUE TITLE
Users are unable to submit a New Request.

### ISSUE THREAD

**Issue by Jingwnpn** [info-461-TBD/ShelterConnect#45]
After filling out all the required information and clicking the Submit button, nothing happens and stays on the same page. New Request is not submitted successfully.
<img width="653" alt="screen shot 2018-06-03 at 6 30 38 pm" src="https://user-images.githubusercontent.com/22405025/40894157-721f136c-675c-11e8-99cd-6824a95d209d.png">

**Comment by sbang97** [comment]
This issue was occurring because our other components were down. The functionality is now up and running.
