### ISSUE TITLE
Filtering does not work properly

### ISSUE THREAD

**Issue by JourneyToTheWes** [info-461-TBD/ShelterConnect#47]
Filtering does not work as expected. For example, selecting by organization: 
![image](https://user-images.githubusercontent.com/15175754/40897187-804fb02e-676e-11e8-9a68-d0c38f4f5971.png)

> These request results are listed. Then if I try to filter by date based off of this organization I should get the same results but sorted in order by the filtered date type.

From the same organization filter and filtering by "Newest to Oldest", I get these values:
![image](https://user-images.githubusercontent.com/15175754/40897312-4094899a-676f-11e8-9f86-eb52c6416e41.png)

**Comment by sbang97** [comment]
Hello, the filters were working properly but were not showing enough information for users to know that they were filtering. Further information is now displayed to allow users to sort the requests.

**Comment by abegel** [comment]
@JourneyToTheWes Can you confirm that this bug is fixed for you?

**Comment by JourneyToTheWes** [comment]
@abegel Yeah the filters work individually. I originally thought the filters were a combination of the two so that you could filter based off of organization and date.
