### ISSUE TITLE
Creating a request doesn't make it show up on the open request list

### ISSUE THREAD

**Issue by JaneQuichocho** [info-461-TBD/ShelterConnect#49]
Reproduction steps:
1. Go to the homepage
2. Click on "Create New Request"
3. Enter the following values:
     -"Food"
     - Expiration date: June 15, 2018
     - Phone: 555-5555
     - email: janeq97@uw.edu
     - address: 123 main st
     - description: i like pie
4. Click on submit

Nothing happens when I click on submit. Is the request suppose to show up on the open request list?

**Comment by abegel** [comment]
I saw the same problem. The New Request dialog did not go away after clicking Submit. Only when I canceled the dialog and refreshed the screen, did I see the new requests I had made.

**Comment by sbang97** [comment]
Submitting a new request now refreshes the page and the request is shown on the list on refresh
