### ISSUE TITLE
uncaught type error: cannot read uid property

### ISSUE THREAD

**Issue by harrybarng** [info-461-TBD/ShelterConnect#51]
![image](https://user-images.githubusercontent.com/37923379/40903974-0df71b46-678e-11e8-8e38-6f724ad8d415.png)

I typed every possible key on the keyboard and copied and pasted them into each box for more than 8 times and clicked submit. This also happens when on empty form too.

Other possible errors are already reported so idk what to put down

**Comment by sbang97** [comment]
Hello, this issue was occurring because we left the "create request" button available for users that were not logged in. This is no longer the case and can be resolved.
