### ISSUE TITLE
There is no way that I can sign up

### ISSUE THREAD

**Issue by juan3674-1532739** [info-461-TBD/ShelterConnect#53]
there is like "Don't yet have an account?" statement but there is no button that allows me to sign up for this page.
![image](https://user-images.githubusercontent.com/25023460/40946375-fdf966e8-6811-11e8-816e-0e6489934f39.png)

**Comment by rykerls** [comment]
Hi @juan3674-1532739,

I have added a link to our registration page from the sign in form. We will redeploy our application soon with this change.

Cheers,
Ryker
