### ISSUE TITLE
Email Subject Field Undefined

### ISSUE THREAD

**Issue by lisakoss** [info-461-TBD/ShelterConnect#56]
When I view the details for a request, either via the "Organizations" tab or the home page, the link to open up a new email to that organization pre-fills the subject of the email with "Complete Request **undefined**". It appears that the state from the web app is not being correctly transferred to the email I open.

[minor]

<img width="1440" alt="screen shot 2018-06-04 at 4 54 20 pm" src="https://user-images.githubusercontent.com/22549728/40947572-3a4df64e-6818-11e8-947c-e9660df39096.png">

**Comment by sbang97** [comment]
This issue has now been resolved. The email subject line is now "Complete Request for" {organization}.
