### ISSUE TITLE
Org Sign Up won't allow valid phone number

### ISSUE THREAD

**Issue by abegel** [info-461-TBD/ShelterConnect#58]
I created an organization with the phone number +1(206)555-1212. When I press the Sign Up button I get the error: Please enter a valid phone number. 

But that number is a valid phone number.

I tried removing the +, and used 1(206)555-1212. But that still didn't work. 

I tried removing all punctuation: 12065551212, but that didn't work either.

Getting rid of the 1 in the phone number made it work: 2065551212. 

Well, now I don't get that error, but clicking on the sign up button doesn't do anything visible and remains on the org sign up page.

**Comment by sunwookang** [comment]
Hey Andrew,
Thanks for letting us know about the issue! We were able to figure it out by changing the Regex formatting that validated the phone number. I added /^(\+)?(1)? to the front of the code that validated the input, which makes it optional for users to input "+", "+1" or "1" before the phone number.

**Comment by abegel** [comment]
Actually, that's not going to solve the general problem of handling country codes in phone numbers: https://en.wikipedia.org/wiki/List_of_country_calling_codes

**Comment by sunwookang** [comment]
Thanks for the catch Andrew! Added international phone number capability with /^(?:(?:\(?(?:00|\+)([1-4]\d\d|[1-9]\d?)\)?)?[\-\.\ \\\/]?)?((?:\(?\d{1,}\)?[\-\.\ \\\/]?){0,})(?:[\-\.\ \\\/]?(?:#|ext\.?|extension|x)[\-\.\ \\\/]?(\d+))?$/i.
