### ISSUE TITLE
Org Sign Up: invalid password is not reported by UI

### ISSUE THREAD

**Issue by abegel** [info-461-TBD/ShelterConnect#59]
When I sign up a new org with an invalid password of 'cow' (too few characters), there is no UI popup displayed after hitting the Sign Up button. 

In the console, I do see an error from Google API:

[Error] Failed to load resource: the server responded with a status of 400 () (signupNewUser, line 0)
[Log] Password should be at least 6 characters (main.8ada45ba.js, line 1)

**Comment by cj-zhang** [comment]
Signup form now alerts the user if their password is shorter than 6 characters.
